--- #YAML:1.0
name:                WWW-Bugzilla3
version:             0.71
abstract:            perl bindings for Bugzilla 3.0 api
license:             ~
author:              
    - Alexey Alexandrov <swined@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    HTTP::Cookies:                 0
    LWP::UserAgent:                0
    RPC::XML:                      0
    RPC::XML::Parser:              0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
